import { NextResponse } from 'next/server';
import { Card } from '@/types/CardType';

const cardSet: Card[] = [
  {
    id: 1,
    name: 'Achlys',
    description:
      'When you slay an opponents creature, your opponent must discard the top card of their deck into their Hell.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/NW5BxB4/Achlys-a-veiled-woman-draped-in-flowing-robes-a.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'SuperRare',
    type: 'Immortal',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 6,
    tinyImage: 'https://i.ibb.co/G9dXCdh/achlys.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 2,
    name: 'Shadow Wyvern',
    description:
      'A wyvern with wings cloaked in darkness, gliding silently through the twilight of a medieval canyon, its piercing gaze striking fear into the hearts of adventurers.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/NrnrLzn/Shadow-Wyvern-Picture-a-shadow-wyvern-with-wing.png',
    inclination: 'Mischief',
    effect:
      'On play, when this creature is summoned by creature drain, your opponent must send the top card of their deck to their Hell.',
    biome: 'Alpine',
    rarity: 'SuperRare',
    type: 'creature',
    effectFunction: '',
    attackPower: 800,
    hp: 500,
    cost: 7,
    tinyImage: 'https://i.ibb.co/qDspvnK/shadow-wyvern.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 2,
    name: 'Shadow Wyvern',
    description:
      'A wyvern with wings cloaked in darkness, gliding silently through the twilight of a medieval canyon, its piercing gaze striking fear into the hearts of adventurers.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/NrnrLzn/Shadow-Wyvern-Picture-a-shadow-wyvern-with-wing.png',
    inclination: 'Mischief',
    effect:
      'On play, when this creature is played by creature drain, your opponent must send the top card of their deck to their Hell.',
    biome: 'Alpine',
    rarity: 'SuperRare',
    type: 'creature',
    effectFunction: '',
    attackPower: 800,
    hp: 500,
    cost: 7,
    tinyImage: 'https://i.ibb.co/qDspvnK/shadow-wyvern.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 3,
    name: 'Mystical Kraken',
    description:
      'A mystical kraken with tentacles wreathed in bioluminescent patterns, lurking in the depths of a medieval ocean cavern, its presence both feared and revered by sailors and sea creatures alike.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/C2nyQ5g/Mystical-Kraken-Imagine-a-mystical-kraken-with.png',
    inclination: 'Mischief',
    effect:
      'When this creature is used as a creature drain, your opponent must send the top card of their deck to their Hell.',
    biome: 'Aquatic',
    rarity: 'SuperRare',
    type: 'creature',
    effectFunction: '',
    attackPower: 400,
    hp: 500,
    cost: 4,
    tinyImage: 'https://i.ibb.co/VJBzgVd/Mystical-kraken.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 3,
    name: 'Mystical Kraken',
    description:
      'A mystical kraken with tentacles wreathed in bioluminescent patterns, lurking in the depths of a medieval ocean cavern, its presence both feared and revered by sailors and sea creatures alike.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/C2nyQ5g/Mystical-Kraken-Imagine-a-mystical-kraken-with.png',
    inclination: 'Mischief',
    effect:
      'When this creature is used as a creature drain, your opponent must send the top card of their deck to their Hell.',
    biome: 'Aquatic',
    rarity: 'SuperRare',
    type: 'creature',
    effectFunction: '',
    attackPower: 400,
    hp: 500,
    cost: 4,
    tinyImage: 'https://i.ibb.co/VJBzgVd/Mystical-kraken.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 4,
    name: 'Crystal Thunderbird',
    description:
      'A thunderbird with wings crackling with electricity, perched on a medieval cliffside, its piercing cries heralding the arrival of storms to the kingdom below.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/VMLYZ1x/Thunderbird-Envision-a-thunderbird-with-wings-c.png',
    inclination: 'Mischief',
    effect:
      'On play, if you have less cards in your hell then your opponent, draw 1 card.',
    biome: 'Alpine',
    rarity: 'SuperRare',
    type: 'creature',
    effectFunction: '',
    attackPower: 200,
    hp: 100,
    cost: 2,
    tinyImage: 'https://i.ibb.co/hCQzrfR/crystal-thunderbird.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 4,
    name: 'Crystal Thunderbird',
    description:
      'A thunderbird with wings crackling with electricity, perched on a medieval cliffside, its piercing cries heralding the arrival of storms to the kingdom below.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/VMLYZ1x/Thunderbird-Envision-a-thunderbird-with-wings-c.png',
    inclination: 'Mischief',
    effect:
      'On play, if you have less cards in your hell then your opponent, draw 1 card.',
    biome: 'Alpine',
    rarity: 'SuperRare',
    type: 'creature',
    effectFunction: '',
    attackPower: 200,
    hp: 100,
    cost: 2,
    tinyImage: 'https://i.ibb.co/hCQzrfR/crystal-thunderbird.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 5,
    name: 'Eternal Guardian',
    description:
      'An eternal guardian with eyes that burn with inner fire, standing vigil over a mystical portal in a medieval enchanted grove, its presence ensuring the balance of magic in the realm.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/MpBLtWL/Eternal-Guardian-Envision-an-eternal-guardian-w.png',
    inclination: 'Mischief',
    effect:
      'If this is the only creature on your side of the field, this creature gains 200 life and attack.',
    biome: 'Forest',
    rarity: 'Uncommon',
    type: 'creature',
    effectFunction: '',
    attackPower: 200,
    hp: 300,
    cost: 2,
    tinyImage: 'https://i.ibb.co/kKZmB73/eternal-guardian.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 5,
    name: 'Eternal Guardian',
    description:
      'An eternal guardian with eyes that burn with inner fire, standing vigil over a mystical portal in a medieval enchanted grove, its presence ensuring the balance of magic in the realm.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/MpBLtWL/Eternal-Guardian-Envision-an-eternal-guardian-w.png',
    inclination: 'Mischief',
    effect:
      'If this is the only creature on your side of the field, this creature gains 200 life and attack.',
    biome: 'Forest',
    rarity: 'Uncommon',
    type: 'creature',
    effectFunction: '',
    attackPower: 200,
    hp: 300,
    cost: 2,
    tinyImage: 'https://i.ibb.co/kKZmB73/eternal-guardian.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 5,
    name: 'Eternal Guardian',
    description:
      'An eternal guardian with eyes that burn with inner fire, standing vigil over a mystical portal in a medieval enchanted grove, its presence ensuring the balance of magic in the realm.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/MpBLtWL/Eternal-Guardian-Envision-an-eternal-guardian-w.png',
    inclination: 'Mischief',
    effect:
      'If this is the only creature on your side of the field, this creature gains 200 life and attack.',
    biome: 'Forest',
    rarity: 'Uncommon',
    type: 'creature',
    effectFunction: '',
    attackPower: 200,
    hp: 300,
    cost: 2,
    tinyImage: 'https://i.ibb.co/kKZmB73/eternal-guardian.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 5,
    name: 'Eternal Guardian',
    description:
      'An eternal guardian with eyes that burn with inner fire, standing vigil over a mystical portal in a medieval enchanted grove, its presence ensuring the balance of magic in the realm.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/MpBLtWL/Eternal-Guardian-Envision-an-eternal-guardian-w.png',
    inclination: 'Mischief',
    effect:
      'If this is the only creature on your side of the field, this creature gains 200 life and attack.',
    biome: 'Forest',
    rarity: 'Uncommon',
    type: 'creature',
    effectFunction: '',
    attackPower: 200,
    hp: 300,
    cost: 2,
    tinyImage: 'https://i.ibb.co/kKZmB73/eternal-guardian.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 6,
    name: 'Celestial Wolf',
    description:
      'Envision a wolf with fur that glows with the light of distant stars, leading a pack through the mystical wilderness of a medieval kingdom.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/qsT7wvb/Celestial-Wolf-Envision-a-wolf-with-fur-that-gl.png',
    inclination: 'Mischief',
    effect: '',
    biome: 'Forest',
    rarity: 'Uncommon',
    type: 'creature',
    effectFunction: '',
    attackPower: 300,
    hp: 100,
    cost: 1,
    tinyImage: 'https://i.ibb.co/b75TMk7/celestial-wolfs.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 6,
    name: 'Celestial Wolf',
    description:
      'Envision a wolf with fur that glows with the light of distant stars, leading a pack through the mystical wilderness of a medieval kingdom.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/qsT7wvb/Celestial-Wolf-Envision-a-wolf-with-fur-that-gl.png',
    inclination: 'Mischief',
    effect: '',
    biome: 'Forest',
    rarity: 'Uncommon',
    type: 'creature',
    effectFunction: '',
    attackPower: 300,
    hp: 100,
    cost: 1,
    tinyImage: 'https://i.ibb.co/b75TMk7/celestial-wolfs.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 6,
    name: 'Celestial Wolf',
    description:
      'Envision a wolf with fur that glows with the light of distant stars, leading a pack through the mystical wilderness of a medieval kingdom.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/qsT7wvb/Celestial-Wolf-Envision-a-wolf-with-fur-that-gl.png',
    inclination: 'Mischief',
    effect: '',
    biome: 'Forest',
    rarity: 'Uncommon',
    type: 'creature',
    effectFunction: '',
    attackPower: 300,
    hp: 100,
    cost: 1,
    tinyImage: 'https://i.ibb.co/b75TMk7/celestial-wolfs.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 6,
    name: 'Celestial Wolf',
    description:
      'A wolf with fur that glows with the light of distant stars, leading a pack through the mystical wilderness of a medieval kingdom.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/qsT7wvb/Celestial-Wolf-Envision-a-wolf-with-fur-that-gl.png',
    inclination: 'Mischief',
    effect: '',
    biome: 'Forest',
    rarity: 'Uncommon',
    type: 'creature',
    effectFunction: '',
    attackPower: 300,
    hp: 100,
    cost: 1,
    tinyImage: 'https://i.ibb.co/b75TMk7/celestial-wolfs.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 7,
    name: 'Thunderous Bear',
    description:
      'A bear with fur that crackles with electricity, roaring with the force of a thunderstorm as it lumbers through the rugged terrain of a medieval mountain range',
    randomNumber: 321,
    image:
      'https://i.ibb.co/7zVPDzh/Thunderous-Bear-Imagine-a-bear-with-fur-that-cr.png',
    inclination: 'Mischief',
    effect:
      'This creature gains 100 life and attack, if there are other Forest biome creatures on your side of the field.',
    biome: 'Forest',
    rarity: 'Uncommon',
    type: 'creature',
    effectFunction: '',
    attackPower: 500,
    hp: 300,
    cost: 4,
    tinyImage: 'https://i.ibb.co/QCZmzVq/thunderous-bear.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 7,
    name: 'Thunderous Bear',
    description:
      'A bear with fur that crackles with electricity, roaring with the force of a thunderstorm as it lumbers through the rugged terrain of a medieval mountain range',
    randomNumber: 321,
    image:
      'https://i.ibb.co/7zVPDzh/Thunderous-Bear-Imagine-a-bear-with-fur-that-cr.png',
    inclination: 'Mischief',
    effect:
      'This creature gains 100 life and attack, if there are other Forest biome creatures on your side of the field.',
    biome: 'Forest',
    rarity: 'Uncommon',
    type: 'creature',
    effectFunction: '',
    attackPower: 500,
    hp: 300,
    cost: 4,
    tinyImage: 'https://i.ibb.co/QCZmzVq/thunderous-bear.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 7,
    name: 'Thunderous Bear',
    description:
      'A bear with fur that crackles with electricity, roaring with the force of a thunderstorm as it lumbers through the rugged terrain of a medieval mountain range',
    randomNumber: 321,
    image:
      'https://i.ibb.co/7zVPDzh/Thunderous-Bear-Imagine-a-bear-with-fur-that-cr.png',
    inclination: 'Mischief',
    effect:
      'This creature gains 100 life and attack, if there are other Forest biome creatures on your side of the field.',
    biome: 'Forest',
    rarity: 'Uncommon',
    type: 'creature',
    effectFunction: '',
    attackPower: 500,
    hp: 300,
    cost: 4,
    tinyImage: 'https://i.ibb.co/QCZmzVq/thunderous-bear.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 7,
    name: 'Thunderous Bear',
    description:
      'A bear with fur that crackles with electricity, roaring with the force of a thunderstorm as it lumbers through the rugged terrain of a medieval mountain range',
    randomNumber: 321,
    image:
      'https://i.ibb.co/7zVPDzh/Thunderous-Bear-Imagine-a-bear-with-fur-that-cr.png',
    inclination: 'Mischief',
    effect:
      'This creature gains 100 life and attack, if there are other Forest biome creatures on your side of the field.',
    biome: 'Forest',
    rarity: 'Uncommon',
    type: 'creature',
    effectFunction: '',
    attackPower: 500,
    hp: 300,
    cost: 4,
    tinyImage: 'https://i.ibb.co/QCZmzVq/thunderous-bear.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 8,
    name: 'Enchanted Owl',
    description:
      'Imagine an owl with eyes that gleam with ancient wisdom, perched on a gnarled branch in the heart of a medieval grove, its hoots echoing through the night.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/72pTp90/Enchanted-Owl-Imagine-an-owl-with-eyes-that-gle.png',
    inclination: 'Mischief',
    effect:
      'On play send 2 cards from you hand into your hell, your opponent must discard the top card of their deck into their hell.',
    biome: 'Forest',
    rarity: 'Uncommon',
    type: 'creature',
    effectFunction: '',
    attackPower: 500,
    hp: 300,
    cost: 2,
    tinyImage: 'https://i.ibb.co/Lk9DVNn/enchanted-owl.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 7,
    name: 'Enchanted Owl',
    description:
      'Imagine an owl with eyes that gleam with ancient wisdom, perched on a gnarled branch in the heart of a medieval grove, its hoots echoing through the night.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/72pTp90/Enchanted-Owl-Imagine-an-owl-with-eyes-that-gle.png',
    inclination: 'Mischief',
    effect:
      'On play send 2 cards from you hand into your hell, your opponent must discard the top card of their deck into their hell.',
    biome: 'Forest',
    rarity: 'Uncommon',
    type: 'creature',
    effectFunction: '',
    attackPower: 500,
    hp: 300,
    cost: 2,
    tinyImage: 'https://i.ibb.co/Lk9DVNn/enchanted-owl.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 7,
    name: 'Enchanted Owl',
    description:
      'Imagine an owl with eyes that gleam with ancient wisdom, perched on a gnarled branch in the heart of a medieval grove, its hoots echoing through the night.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/72pTp90/Enchanted-Owl-Imagine-an-owl-with-eyes-that-gle.png',
    inclination: 'Mischief',
    effect:
      'On play send 2 cards from you hand into your hell, your opponent must discard the top card of their deck into their hell.',
    biome: 'Forest',
    rarity: 'Uncommon',
    type: 'creature',
    effectFunction: '',
    attackPower: 500,
    hp: 300,
    cost: 2,
    tinyImage: 'https://i.ibb.co/Lk9DVNn/enchanted-owl.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 7,
    name: 'Enchanted Owl',
    description:
      'Imagine an owl with eyes that gleam with ancient wisdom, perched on a gnarled branch in the heart of a medieval grove, its hoots echoing through the night.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/72pTp90/Enchanted-Owl-Imagine-an-owl-with-eyes-that-gle.png',
    inclination: 'Mischief',
    effect:
      'On play send 2 cards from you hand into your hell, your opponent must discard the top card of their deck into their hell.',
    biome: 'Forest',
    rarity: 'Uncommon',
    type: 'creature',
    effectFunction: '',
    attackPower: 500,
    hp: 300,
    cost: 2,
    tinyImage: 'https://i.ibb.co/Lk9DVNn/enchanted-owl.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 9,
    name: 'Mystic Rainbow Phoenix',
    description:
      'A mystic phoenix with feathers ablaze in rainbow hues, soaring above a medieval village, its fiery tail trailing like a comet through the night sky.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/pdP5trS/Mystic-Phoenix-Picture-a-mystic-phoenix-with-fe.png',
    inclination: 'Mischief',
    effect: '',
    biome: 'Alpine',
    rarity: 'Common',
    type: 'creature',
    effectFunction: '',
    attackPower: 500,
    hp: 400,
    cost: 3,
    tinyImage: 'https://i.ibb.co/7QKWWGt/mystic-rainbow.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 8,
    name: 'Mystic Rainbow Phoenix',
    description:
      'A mystic phoenix with feathers ablaze in rainbow hues, soaring above a medieval village, its fiery tail trailing like a comet through the night sky.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/pdP5trS/Mystic-Phoenix-Picture-a-mystic-phoenix-with-fe.png',
    inclination: 'Mischief',
    effect: '',
    biome: 'Alpine',
    rarity: 'Common',
    type: 'creature',
    effectFunction: '',
    attackPower: 500,
    hp: 400,
    cost: 3,
    tinyImage: 'https://i.ibb.co/7QKWWGt/mystic-rainbow.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 8,
    name: 'Mystic Rainbow Phoenix',
    description:
      'A mystic phoenix with feathers ablaze in rainbow hues, soaring above a medieval village, its fiery tail trailing like a comet through the night sky.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/pdP5trS/Mystic-Phoenix-Picture-a-mystic-phoenix-with-fe.png',
    inclination: 'Mischief',
    effect: '',
    biome: 'Alpine',
    rarity: 'Common',
    type: 'creature',
    effectFunction: '',
    attackPower: 500,
    hp: 400,
    cost: 3,
    tinyImage: 'https://i.ibb.co/7QKWWGt/mystic-rainbow.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 8,
    name: 'Mystic Rainbow Phoenix',
    description:
      'A mystic phoenix with feathers ablaze in rainbow hues, soaring above a medieval village, its fiery tail trailing like a comet through the night sky.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/pdP5trS/Mystic-Phoenix-Picture-a-mystic-phoenix-with-fe.png',
    inclination: 'Mischief',
    effect: '',
    biome: 'Alpine',
    rarity: 'Uncommon',
    type: 'creature',
    effectFunction: '',
    attackPower: 500,
    hp: 400,
    cost: 3,
    tinyImage: 'https://i.ibb.co/7QKWWGt/mystic-rainbow.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 10,
    name: 'Ancient Frost Phoenix',
    description:
      'A frost phoenix with icy feathers, rising from the snow-covered ruins of a medieval castle, its wings casting shimmering reflections on the frozen landscape.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/JFsg9yV/Frost-Phoenix-Picture-a-frost-phoenix-with-icy.png',
    inclination: 'Mischief',
    effect:
      'On play, you may play "Mystic Rainbow Phoenix" from your hand for no cost.',
    biome: 'Tundra',
    rarity: 'Common',
    type: 'creature',
    effectFunction: '',
    attackPower: 500,
    hp: 400,
    cost: 4,
    tinyImage: 'https://i.ibb.co/xg4cydy/ancient-frost.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 9,
    name: 'Ancient Frost Phoenix',
    description:
      'A frost phoenix with icy feathers, rising from the snow-covered ruins of a medieval castle, its wings casting shimmering reflections on the frozen landscape.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/JFsg9yV/Frost-Phoenix-Picture-a-frost-phoenix-with-icy.png',
    inclination: 'Mischief',
    effect:
      'On play, you may play "Mystic Rainbow Phoenix" from your hand for no cost.',
    biome: 'Tundra',
    rarity: 'Common',
    type: 'creature',
    effectFunction: '',
    attackPower: 500,
    hp: 400,
    cost: 4,
    tinyImage: 'https://i.ibb.co/xg4cydy/ancient-frost.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 9,
    name: 'Ancient Frost Phoenix',
    description:
      'A frost phoenix with icy feathers, rising from the snow-covered ruins of a medieval castle, its wings casting shimmering reflections on the frozen landscape.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/JFsg9yV/Frost-Phoenix-Picture-a-frost-phoenix-with-icy.png',
    inclination: 'Mischief',
    effect:
      'On play, you may play "Mystic Rainbow Phoenix" from your hand for no cost.',
    biome: 'Tundra',
    rarity: 'Common',
    type: 'creature',
    effectFunction: '',
    attackPower: 500,
    hp: 400,
    cost: 4,
    tinyImage: 'https://i.ibb.co/xg4cydy/ancient-frost.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 9,
    name: 'Ancient Frost Phoenix',
    description:
      'A frost phoenix with icy feathers, rising from the snow-covered ruins of a medieval castle, its wings casting shimmering reflections on the frozen landscape.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/JFsg9yV/Frost-Phoenix-Picture-a-frost-phoenix-with-icy.png',
    inclination: 'Mischief',
    effect:
      'On play, you may play "Mystic Rainbow Phoenix" from your hand for no cost.',
    biome: 'Tundra',
    rarity: 'Common',
    type: 'creature',
    effectFunction: '',
    attackPower: 500,
    hp: 400,
    cost: 4,
    tinyImage: 'https://i.ibb.co/xg4cydy/ancient-frost.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 11,
    name: 'Crystal Fox',
    description:
      'Envision a fox with fur that glistens like crystal, darting through the moonlit streets of a medieval village, its graceful movements a testament to its otherworldly nature.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/3p9pZZV/Crystal-Fox-Envision-a-fox-with-fur-that-gliste.png',
    inclination: 'Mischief',
    effect:
      'On play, look at the top 5 cards of your deck, if a creature has the biome of "Forest" you may add that card into your hand, return the cards to the top of your deck in any order.',
    biome: 'Forest',
    rarity: 'Common',
    type: 'creature',
    effectFunction: '',
    attackPower: 200,
    hp: 200,
    cost: 2,
    tinyImage: 'https://i.ibb.co/N9tFWgk/crystal-fox.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 10,
    name: 'Crystal Fox',
    description:
      'Envision a fox with fur that glistens like crystal, darting through the moonlit streets of a medieval village, its graceful movements a testament to its otherworldly nature.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/3p9pZZV/Crystal-Fox-Envision-a-fox-with-fur-that-gliste.png',
    inclination: 'Mischief',
    effect:
      'On play, look at the top 5 cards of your deck, if a creature has the biome of "Forest" you may add that card into your hand, return the cards to the top of your deck in any order.',
    biome: 'Forest',
    rarity: 'Common',
    type: 'creature',
    effectFunction: '',
    attackPower: 200,
    hp: 200,
    cost: 2,
    tinyImage: 'https://i.ibb.co/N9tFWgk/crystal-fox.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 10,
    name: 'Crystal Fox',
    description:
      'Envision a fox with fur that glistens like crystal, darting through the moonlit streets of a medieval village, its graceful movements a testament to its otherworldly nature.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/3p9pZZV/Crystal-Fox-Envision-a-fox-with-fur-that-gliste.png',
    inclination: 'Mischief',
    effect:
      'On play, look at the top 5 cards of your deck, if a creature has the biome of "Forest" you may add that card into your hand, return the cards to the top of your deck in any order.',
    biome: 'Forest',
    rarity: 'Common',
    type: 'creature',
    effectFunction: '',
    attackPower: 200,
    hp: 200,
    cost: 2,
    tinyImage: 'https://i.ibb.co/N9tFWgk/crystal-fox.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 10,
    name: 'Crystal Fox',
    description:
      'Envision a fox with fur that glistens like crystal, darting through the moonlit streets of a medieval village, its graceful movements a testament to its otherworldly nature.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/3p9pZZV/Crystal-Fox-Envision-a-fox-with-fur-that-gliste.png',
    inclination: 'Mischief',
    effect:
      'On play, look at the top 5 cards of your deck, if a creature has the biome of "Forest" you may add that card into your hand, return the cards to the top of your deck in any order.',
    biome: 'Forest',
    rarity: 'Common',
    type: 'creature',
    effectFunction: '',
    attackPower: 200,
    hp: 200,
    cost: 2,
    tinyImage: 'https://i.ibb.co/N9tFWgk/crystal-fox.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 12,
    name: 'Mystic Amethyst Tiger',
    description:
      'A purple tiger with stripes that ripple with magical energy and scales, stalking through the dark night glades of a medieval jungle, its presence commanding respect from all who encounter it.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/kG4C9rq/A-captivating-animestyle-illustration-of-a-myst.png',
    inclination: 'Mischief',
    effect: '',
    biome: 'Jungle',
    rarity: 'Common',
    type: 'creature',
    effectFunction: '',
    attackPower: 800,
    hp: 500,
    cost: 6,
    tinyImage: 'https://i.ibb.co/Czb2D1j/mystic-tiger.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 12,
    name: 'Mystic Amethyst Tiger',
    description:
      'A purple tiger with stripes that ripple with magical energy and scales, stalking through the dark night glades of a medieval jungle, its presence commanding respect from all who encounter it.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/kG4C9rq/A-captivating-animestyle-illustration-of-a-myst.png',
    inclination: 'Mischief',
    effect: '',
    biome: 'Jungle',
    rarity: 'Common',
    type: 'creature',
    effectFunction: '',
    attackPower: 800,
    hp: 500,
    cost: 6,
    tinyImage: 'https://i.ibb.co/Czb2D1j/mystic-tiger.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 11,
    name: 'Mystic Amethyst Tiger',
    description:
      'A purple tiger with stripes that ripple with magical energy and scales, stalking through the dark night glades of a medieval jungle, its presence commanding respect from all who encounter it.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/kG4C9rq/A-captivating-animestyle-illustration-of-a-myst.png',
    inclination: 'Mischief',
    effect: '',
    biome: 'Jungle',
    rarity: 'Common',
    type: 'creature',
    effectFunction: '',
    attackPower: 800,
    hp: 500,
    cost: 6,
    tinyImage: 'https://i.ibb.co/Czb2D1j/mystic-tiger.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 11,
    name: 'Mystic Amethyst Tiger',
    description:
      'A purple tiger with stripes that ripple with magical energy and scales, stalking through the dark night glades of a medieval jungle, its presence commanding respect from all who encounter it.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/kG4C9rq/A-captivating-animestyle-illustration-of-a-myst.png',
    inclination: 'Mischief',
    effect: '',
    biome: 'Jungle',
    rarity: 'Common',
    type: 'creature',
    effectFunction: '',
    attackPower: 800,
    hp: 500,
    cost: 6,
    tinyImage: 'https://i.ibb.co/Czb2D1j/mystic-tiger.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 13,
    name: "Achlys' Embrace",
    description: 'Negate the summoning of a creature from hell.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/ypWTBgz/Achlys-looking-to-the-side-a-veiled-woman-drape.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'Common',
    type: 'Divine Intervention',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 3,
    tinyImage: 'https://i.ibb.co/MRbNZsh/embrace.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 12,
    name: "Achlys' Embrace",
    description: 'Negate the summoning of a creature from hell.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/ypWTBgz/Achlys-looking-to-the-side-a-veiled-woman-drape.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'Common',
    type: 'Divine Intervention',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 3,
    tinyImage: 'https://i.ibb.co/MRbNZsh/embrace.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 12,
    name: "Achlys' Embrace",
    description: 'Negate the summoning of a creature from hell.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/ypWTBgz/Achlys-looking-to-the-side-a-veiled-woman-drape.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'Common',
    type: 'Divine Intervention',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 3,
    tinyImage: 'https://i.ibb.co/MRbNZsh/embrace.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 11,
    name: "Achlys' Embrace",
    description: 'Negate the summoning of a creature from hell.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/ypWTBgz/Achlys-looking-to-the-side-a-veiled-woman-drape.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'Uncommon',
    type: 'Divine Intervention',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 3,
    tinyImage: 'https://i.ibb.co/MRbNZsh/embrace.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 14,
    name: 'Veil of Achlys',
    description:
      'Equip this card to a creature, this creature can not be slayed in battle.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/qFHzcby/A-captivating-3-D-render-of-the-Veil-of-Achlys-w.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'Uncommon',
    type: 'Relic',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 2,
    tinyImage: 'https://i.ibb.co/HYd4zN5/veil.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 12,
    name: 'Veil of Achlys',
    description:
      'Equip this card to a creature, this creature can not be slayed in battle.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/qFHzcby/A-captivating-3-D-render-of-the-Veil-of-Achlys-w.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'Uncommon',
    type: 'Relic',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 2,
    tinyImage: 'https://i.ibb.co/HYd4zN5/veil.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 12,
    name: 'Veil of Achlys',
    description:
      'Equip this card to a creature, this creature can not be slayed in battle.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/qFHzcby/A-captivating-3-D-render-of-the-Veil-of-Achlys-w.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'Uncommon',
    type: 'Relic',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 2,
    tinyImage: 'https://i.ibb.co/HYd4zN5/veil.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 12,
    name: 'Veil of Achlys',
    description:
      'Equip this card to a creature, this creature can not be slayed in battle.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/qFHzcby/A-captivating-3-D-render-of-the-Veil-of-Achlys-w.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'Uncommon',
    type: 'Relic',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 2,
    tinyImage: 'https://i.ibb.co/HYd4zN5/veil.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 15,
    name: "Achlys' Mist",
    description: 'Your opponent may not attack on their next turn.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/3kPDvz6/Design-artwork-featuring-the-Mist-of-Achlys-a-s.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'Uncommon',
    type: 'Relic',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 4,
    tinyImage: 'https://i.ibb.co/pXXVyQ3/mist.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 13,
    name: "Achlys' Mist",
    description: 'Your opponent may not attack in their next turn.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/3kPDvz6/Design-artwork-featuring-the-Mist-of-Achlys-a-s.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'Uncommon',
    type: 'Relic',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 4,
    tinyImage: 'https://i.ibb.co/pXXVyQ3/mist.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 13,
    name: "Achlys' Mist",
    description: 'Your opponent may not attack in their next turn.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/3kPDvz6/Design-artwork-featuring-the-Mist-of-Achlys-a-s.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'Uncommon',
    type: 'Relic',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 4,
    tinyImage: 'https://i.ibb.co/pXXVyQ3/mist.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 13,
    name: "Achlys' Mist",
    description: 'Your opponent may not attack in their next turn.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/3kPDvz6/Design-artwork-featuring-the-Mist-of-Achlys-a-s.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'Uncommon',
    type: 'Relic',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 4,
    tinyImage: 'https://i.ibb.co/pXXVyQ3/mist.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 16,
    name: 'Nectar of Mischief',
    description:
      'Only one nectar may be used per turn, unless otherwise specified by another card effect.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/HnjGXGs/can-you-generate-a-black-nectar-in-a-intricate-g.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'Nectar',
    type: 'Nectar',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 0,
    tinyImage: '',
    set: 'Nightmare Requiem',
  },
  {
    id: 14,
    name: 'Nectar of Mischief',
    description:
      'Only one nectar may be used per turn, unless otherwise specified by another card effect.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/HnjGXGs/can-you-generate-a-black-nectar-in-a-intricate-g.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'Nectar',
    type: 'Nectar',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 0,
    tinyImage: 'https://i.ibb.co/rG0QLNn/nectar-mischief.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 12,
    name: 'Nectar of Mischief',
    description:
      'Only one nectar may be used per turn, unless otherwise specified by another card effect.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/HnjGXGs/can-you-generate-a-black-nectar-in-a-intricate-g.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'Nectar',
    type: 'Nectar',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 0,
    tinyImage: 'https://i.ibb.co/rG0QLNn/nectar-mischief.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 12,
    name: 'Nectar of Mischief',
    description:
      'Only one nectar may be used per turn, unless otherwise specified by another card effect.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/HnjGXGs/can-you-generate-a-black-nectar-in-a-intricate-g.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'Nectar',
    type: 'Nectar',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 0,
    tinyImage: 'https://i.ibb.co/rG0QLNn/nectar-mischief.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 12,
    name: 'Nectar of Mischief',
    description:
      'Only one nectar may be used per turn, unless otherwise specified by another card effect.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/HnjGXGs/can-you-generate-a-black-nectar-in-a-intricate-g.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'Nectar',
    type: 'Nectar',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 0,
    tinyImage: 'https://i.ibb.co/rG0QLNn/nectar-mischief.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 12,
    name: 'Nectar of Mischief',
    description:
      'Only one nectar may be used per turn, unless otherwise specified by another card effect.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/HnjGXGs/can-you-generate-a-black-nectar-in-a-intricate-g.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'Nectar',
    type: 'Nectar',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 0,
    tinyImage: 'https://i.ibb.co/rG0QLNn/nectar-mischief.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 12,
    name: 'Nectar of Mischief',
    description:
      'Only one nectar may be used per turn, unless otherwise specified by another card effect.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/HnjGXGs/can-you-generate-a-black-nectar-in-a-intricate-g.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'Nectar',
    type: 'Nectar',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 0,
    tinyImage: 'https://i.ibb.co/rG0QLNn/nectar-mischief.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 12,
    name: 'Nectar of Mischief',
    description:
      'Only one nectar may be used per turn, unless otherwise specified by another card effect.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/HnjGXGs/can-you-generate-a-black-nectar-in-a-intricate-g.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'Nectar',
    type: 'Nectar',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 0,
    tinyImage: 'https://i.ibb.co/rG0QLNn/nectar-mischief.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 12,
    name: 'Nectar of Mischief',
    description:
      'Only one nectar may be used per turn, unless otherwise specified by another card effect.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/HnjGXGs/can-you-generate-a-black-nectar-in-a-intricate-g.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'Nectar',
    type: 'Nectar',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 0,
    tinyImage: 'https://i.ibb.co/rG0QLNn/nectar-mischief.png',
    set: 'Nightmare Requiem',
  },
  {
    id: 12,
    name: 'Nectar of Mischief',
    description:
      'Only one nectar may be used per turn, unless otherwise specified by another card effect.',
    randomNumber: 321,
    image:
      'https://i.ibb.co/HnjGXGs/can-you-generate-a-black-nectar-in-a-intricate-g.png',
    inclination: 'Mischief',
    effect: '',
    biome: '',
    rarity: 'Nectar',
    type: 'Nectar',
    effectFunction: '',
    attackPower: 0,
    hp: 0,
    cost: 0,
    tinyImage: 'https://i.ibb.co/rG0QLNn/nectar-mischief.png',
    set: 'Nightmare Requiem',
  },
];

export async function GET(req: Request) {
  console.log(cardSet.length);
  return NextResponse.json(cardSet);
}
